server:
  port: 9002
spring:
  application:
    name: dynamic-route-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "087032"
    url: jdbc:mysql://127.0.0.1:3306/db_demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&allowMultiQueries=true
  redis:
    host: 127.0.0.1
    port: 6379

# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:6699/eureka/
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置mapper xml文件的路径
  mapper-locations: classpath:com/jcp/dynamic/route/mapper/*.xml

jcp:
  routeKey: "ROUTE_KEY"